import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import BackToTop from "./components/BackToTop";
import ScrollToTop from "./components/ScrollToTop";

export const metadata: Metadata = {
    title: "FOSO SOFT",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<    {
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
                <BackToTop />
                <ScrollToTop />
            </body>
        </html>
    );
}
